config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
  
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 root "home#index"


  resources :authors do
    resources :books
  end
resources :suppliers
resources :customers do
  resources :orders do
  resources :reviews, only: [:new, :create, :index, :show]
end

  
end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :orders
    has_many :reviews
    has_one_attached :avatar


    validates :firstname, presence: true
    validates :lastname, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  end
  

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
   def index
      @customers = Customer.all
    end
 
     def show
        @customer = Customer.find(params[:id])
      end
    
      def new
        @customer = Customer.new
      end
    
      def create
        @customer = Customer.new(customer_params)
    
        if @customer.save
          redirect_to @customer
        else
          render :new, status: :unprocessable_entity
        end
      end


      def full_name
        "#{first_name} #{last_name}"
      end
    
      def edit
        @customer = Customer.find(params[:id])
      end
    
      def update
        @customer = Customer.find(params[:id])
    
        if @customer.update(customer_params)
          redirect_to @customer
        else
          render :edit, status: :unprocessable_entity
        end
      end
    
      def destroy
        @customer = Customer.find(params[:id])
        @customer.destroy
    
        redirect_to root_path, status: :see_other
      end
    
      private
        def customer_params
          params.require(:customer).permit(:firstname , :lastname , :email, :password, :password_confirmation)
        end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_with model: customer do |form| %>
    <div>
      <%= form.label :firstname %><br>
      <%= form.text_field :firstname %>
      <% customer.errors.full_messages_for(:firstname).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>

    <div>
      <%= form.label :lastname %><br>
      <%= form.text_field :lastname %>
      <% customer.errors.full_messages_for(:lastname).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>


    <div>
      <%= form.label :email %><br>
      <%= form.email_field :email %>
      <% customer.errors.full_messages_for(:email).each do |message| %>
        <div><%= message %></div>
       <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render "form", customer: @customer %>

app/views/customers/index.html.erb
<% if current_customer.present? %>
  <h1>Welcome,   
  <% if current_customer.avatar.attachment.present? %>
    <%= image_tag current_customer.avatar, class: 'avatar-image' %>
  <% end %>

  <%= link_to "#{current_customer.firstname} #{current_customer.lastname}", customer_path(current_customer) %></h1>
  <%= link_to "New Order", new_customer_order_path(current_customer) %> --
  <%= link_to "Show Orders", customer_orders_path(current_customer) %> --
<% else %>
  <p>No customer logged in.</p>
<% end %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render "form", customer: @customer %>

app/views/customers/show.html.erb
<h1>name:<%= "#{current_customer.firstname} #{current_customer.lastname}" %></h1>
<h2>email:<%= current_customer.email %></h2>



<ul>
  <li><%= link_to "Edit",  edit_customer_path(current_customer) %></li>
  <li><%= link_to "Destroy",customer_path(current_customer), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>