config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
  
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 root "home#index"


  resources :authors do
    resources :books
  end
resources :suppliers
resources :customers do
  resources :orders do
  resources :reviews, only: [:new, :create, :index, :show]
end

  
end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :supplier
    belongs_to :author
    has_many :reviews
    has_and_belongs_to_many :orders, join_table: 'books_orders'
    has_one_attached :avatar

  
    validates :title, presence: true
    validates :year_published, presence: true, inclusion: { in: (Date.current.year - 100)..Date.current.year }
    validates :price, presence: true, numericality: { greater_than: 0 }
    validates :out_of_print, inclusion: { in: [true, false] }
    validates :author_id, presence: true
    validates :supplier_id, presence: true

  end
  

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_author!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_author, only: [:new, :create]
  before_action :set_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = @author.books.build
  end

  def create
    @book = @author.books.build(book_params)

    if @book.save
      redirect_to author_books_path(current_author), notice: 'Book was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    # The set_book before_action ensures @book is set
  end

  def update
    if @book.update(book_params)
      redirect_to author_books_path(current_author), notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to author_books_path(current_author), notice: 'Book was successfully destroyed.'
  end

  private

  def set_author
    @author = current_author
  end

  def set_book
    @book = current_author.books.find(params[:id])
  end

  def book_params
    params.require(:book).permit(
      :title,
      :supplier_id,  
      :year_published,
      :out_of_print,
      :price,
      :avatar
    )
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: [@author, @book], local: true) do |form| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, autofocus: true %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% @book.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :supplier_id %>
    <%= form.collection_select :supplier_id, Supplier.all, :id, :name, { prompt: "Select a supplier" } %>
    <% @book.errors.full_messages_for(:supplier_id).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :year_published, 'Year Published' %>
    <%= form.select :year_published, options_for_select((Date.current.year - 100)..Date.current.year), prompt: 'Choose a year' %>
  </div>


  <div class="field">
    <%= form.label :out_of_print, 'Out of Print' %>
    <%= form.radio_button :out_of_print, true %> <%= label_tag 'out_of_print_true', 'Yes' %>
    <%= form.radio_button :out_of_print, false %> <%= label_tag 'out_of_print_false', 'No' %>
  </div>

  <div class="field">
    <%= form.label :price, 'Price' %>
    <%= form.number_field :price, step: '0.01', min: 0 %>
  </div>

  <!-- Add other book attributes as needed -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<!-- app/views/books/edit.html.erb -->

<h1>Edit Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<h1>Books</h1>
 
<%= link_to 'Sort by Title (A-Z)', author_books_path(current_author, sort: 'title_asc') %>
<%= link_to 'Sort by Price (Low to High)', author_books_path(current_author, sort: 'price_low_high') %>
<%= link_to 'Sort by Price (High to Low)', author_books_path(current_author, sort: 'price_high_low') %>

<h2>My Books</h2>
  <ul>
    <% current_author.books.each do |book| %>
      <li>
        <% if book.avatar.attachment.present? %>
          <%= image_tag book.avatar, class: 'avatar-image' %>
        <% end %>
        <%= link_to book.title, author_book_path(current_author, book)%>
      </li>
    <% end %>
  </ul>

<%= link_to "New Book", new_author_book_path(current_author) %>

app/views/books/new.html.erb
<!-- app/views/books/new.html.erb -->

<h1>New Book</h1>

<%= render 'form' %>

app/views/books/show.html.erb
<h1>title:<%= @book.title %></h1>
<h3>price:<%= @book.price %></h1>
<h3>year_published:<%= @book.year_published %></h1>





<ul>
  <li><%= link_to "Edit",  edit_author_book_path(current_author, book) %></li>
  <li><%= link_to "Destroy",author_book_path(current_author, book), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>