config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  devise_for :authors
  
  # get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 root "home#index"


  resources :authors do
    resources :books
  end
resources :suppliers
resources :customers do
  resources :orders do
  resources :reviews, only: [:new, :create, :index, :show]
end

  
end


  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :books
    has_many :authors, through: :books
    
    validates :name, presence: true

  end
  

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
   def index
      @suppliers = Supplier.all
    end
    
     def show
        @supplier = Supplier.find(params[:id])
      end
    
      def new
        @supplier = Supplier.new
      end
    
      def create
        @supplier = Supplier.new(supplier_params)
    
        if @supplier.save
          redirect_to @supplier
        else
          render :new, status: :unprocessable_entity
        end
      end
    
      def edit
        @supplier = Supplier.find(params[:id])
      end
    
      def update
        @supplier = Supplier.find(params[:id])
    
        if @supplier.update(supplier_params)
          redirect_to @supplier
        else
          render :edit, status: :unprocessable_entity
        end
      end
    
      def destroy
        @supplier = Supplier.find(params[:id])
        @supplier.destroy
    
        redirect_to root_path, status: :see_other
      end
    
      private
        def supplier_params
          params.require(:supplier).permit(:name)
        end
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/suppliers/_form.html.erb
<%= form_with model: supplier do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% supplier.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>

app/views/suppliers/edit.html.erb
<h1>Edit Supplier</h1>

<%= render "form", supplier: @supplier %>

app/views/suppliers/index.html.erb
<h1>Suppliers</h1>

<ul>
  <% @suppliers.each do |supplier| %>
    <li>
      <%= link_to supplier.name, supplier %>
    </li>
  <% end %>
</ul>
<%= link_to "New Supplier", new_supplier_path %>

app/views/suppliers/new.html.erb
<h1>New Supplier</h1>

<%= render "form", supplier: @supplier %>

app/views/suppliers/show.html.erb
<h1><%= @supplier.name %></h1>


<ul>
  <li><%= link_to "Edit", edit_supplier_path(@supplier) %></li>
  <li><%= link_to "Destroy", supplier_path(@supplier), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>